### ISSUE TITLE
エラー

### ISSUE THREAD

**Issue by touyou** [mcasashi-aso/ClassSchedule#3]
```
reason: '[<UITableView 0x7facee835c00> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key emptyDataSetDelegate.'
```

こっちで動かしたらこのエラーが出てたから、遷移しない一番の原因はこれだと思う。
Storyboard確認してみるとたしかにemptyDataSetDelegateとemptyDataSetSourceが設定されてしまってたので消してあげよう。

（もしDZNEmptyDataSetとかを使っててということであればコードのほうでちゃんとDelegateメソッドとかを書いてあげてから、コード側で設定するようにするのが確実だと思う。）

**Comment by mcasashi-aso** [comment]
あー消したの忘れてた
色々あってまだXcodeアプデできてないから今日中にアプデして直す
ありがとう
